services:
  redis:
    image: redis:alpine
    container_name: gomegle-redis
    env_file: .env
    networks:
      - app
  gomegle:
    build:
      context: .
    container_name: gomegle
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=23234
      - REDIS_URL=gomegle-redis:6379
    networks:
      - app
    depends_on:
      - redis
    ports:
      - 23234:23234
  gomegle-web:
    build:
      context: ./frontend
    container_name: gomegle-web
    env_file: ./frontend/.env
    environment:
      - REDIS_URL=gomegle-redis:6379
    networks:
      - app
    ports:
      - 3000:3000
networks:
  app:
    driver: bridge
