apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.backend.sshSecret }}
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: {{ .Values.externalSecret.sshKey.privateKeyRemoteRef }}
    - secretKey: id_ed25519.pub
      remoteRef:
        key: {{ .Values.externalSecret.sshKey.publicKeyRemoteRef }}
