backend:
  replicas: 2
  image:
    repository: ghcr.io/johan253/gomegle
    tag: latest
    pullPolicy: Always
  port: 23234
  sshSecret: gomegle-ssh-hostkey
  env:
    HOST: "0.0.0.0"
    REDIS_URL: "redis://gomegle-redis:6379"

redis:
  replicas: 1
  image:
    repository: redis
    tag: alpine

web:
  replicas: 2
  image:
    repository: ghcr.io/johan253/gomegle-web
    tag: latest
    pullPolicy: Always
  port: 3000
  env:
    HOST: "0.0.0.0"
    REDIS_URL: "redis://gomegle-redis:6379"

externalSecret:
  secretStore:
    name: infisical
    kind: ClusterSecretStore
  sshKey:
    privateKeyRemoteRef: gomegle-ssh-priv
    publicKeyRemoteRef: gomegle-ssh-pub

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - gomegle.sh
    - www.gomegle.sh
  tls:
    secretName: gomegle-tls
