backend:
  replicas: 2
  image:
    repository: ghcr.io/johan253/gomegle
    tag: latest
    pullPolicy: Always
  port: 23234
  host: "0.0.0.0"
  redisUrl: "gomegle-redis:6379"

redis:
  replicas: 1
  image:
    repository: redis
    tag: alpine

web:
  replicas: 2
  image:
    repository: ghcr.io/johan253/gomegle-web
    tag: latest
    pullPolicy: Always
  port: 3000
  host: "0.0.0.0"
  redisUrl: "redis://gomegle-redis:6379"

externalSecret:
  secretName: gomegle-ssh-hostkey
  secretStore:
    name: infisical
    kind: ClusterSecretStore
  sshKey:
    privateKeyRemoteRef: /gomegle/ssh-priv
    publicKeyRemoteRef: /gomegle/ssh-pub

ingress:
  enabled: false
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - gomegle.sh
    - www.gomegle.sh
  tls:
    issuer:
      name: letsencrypt-http
      kind: ClusterIssuer
    secretName: gomegle-tls
  rateLimit:
    enabled: true
    average: 50
    burst: 100
    period: 1s
    
# Define any additional Kubernetes objects you want to create with this chart here. This can be used for things like ConfigMaps, Secrets, etc.
extraObjects: []
