name: Build and Test App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: goinstall

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Build application
        run: make build

  server:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Test server run
        run: make test-server
